### ISSUE TITLE
Need to add `async-trait` crate to own `Cargo.toml`

### ISSUE THREAD

**Issue by D4nte** [thomaseizinger/rust-jsonrpc-client#6]
To use `rust-jsonrpc-client` I need to add `async-trait` to my `Cargo.toml` file.

This is cumbersome.

Instead, I would suggest that `rust-jsonrpc-client` re-exports `async_trait` and uses the re-export in the generated code: `jsonrpc_client::async_trait`.

**Comment by thomaseizinger** [comment]
Good idea, thank you!
